# Jekyll Configuration for Lou's Recipe Collection
title: "Recipes From Lou"
description: "A 50-year collection of cherished family recipes from Lou's kitchen"
url: "https://heygarrison.github.io"
baseurl: "/RecipesFromLou"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Header navigation - only show homepage
header_pages:
  - index.md

# Exclude files from build
exclude:
  - RAW/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Default layouts for recipe files
defaults:
  - scope:
      path: "converted"
      type: "pages"
    values:
      layout: "recipe"
      show_in_nav: false