# Jekyll Configuration for Lou's Recipe Collection
title: "Recipes From Lou"
description: "A 50-year collection of cherished family recipes from Lou's kitchen"
url: "https://heygarrison.github.io"
baseurl: "/RecipesFromLou"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for organized recipes
collections:
  recipes:
    output: true
    permalink: /:collection/:name/

# Navigation
header_pages:
  - introduction.md
  - recipes.md
  - about.md

# Exclude files from build
exclude:
  - RAW/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Include converted directory
include:
  - converted

# Default layouts
defaults:
  - scope:
      path: "converted"
      type: "pages"
    values:
      layout: "recipe"
  - scope:
      path: "converted/breads"
      type: "pages"  
    values:
      layout: "recipe"
      category: "Breads"
  - scope:
      path: "converted/cakes"
      type: "pages"
    values:
      layout: "recipe" 
      category: "Cakes"
  - scope:
      path: "converted/poultry"
      type: "pages"
    values:
      layout: "recipe"
      category: "Poultry"